name: Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - name: Download
      run: npm install
    - name: Documentation setup
      run: npm i jsdoc vue-template-compiler jsdoc-vuejs
      continue-on-error: true

    - name: Create ENV file with commit message
      run: |
        echo VUE_APP_COMMIT_MESSAGE = \"$(git log --format=%B -n 1 ${{ github.event.after }})\" > .env.local
        echo VUE_APP_RELEASE_DATE = \"$(git log --date=format:"%e.%C.%Y %H:%M:%S" --pretty=format:%ad -n 1 ${{ github.event.after }})\" >> .env.local
      
    - name: Build
      run: npm run Build-Modern
    - name: Documentation Build
      run: npm run Documentation
      continue-on-error: true
      
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: 126701.w1.wedos.net
        FTP_USERNAME: w126701_dev
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: dist
        ARGS: --delete
