name: 'Stable Version Publish'
on:
  push:
    branches:
    - 'stable'
  pull_request:
    branches:
     - 'stable'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - name: Download
      run: npm install
      
    - name: Build
      run: npm run Build-Modern
      
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: 126701.w1.wedos.net
        FTP_USERNAME: w126701_stable
        FTP_PASSWORD: ${{ secrets.FTP_STABLE_PASSWORD }}
        LOCAL_DIR: dist
        ARGS: --delete
